# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  repositories:
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup
    pki: https://github.com/simp/pupmod-simp-pki
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
    vox_selinux:
      repo: https://github.com/simp/pupmod-voxpupuli-selinux
      branch: simp-master
    selinux: https://github.com/simp/pupmod-simp-selinux

# Testing
    auditd: https://github.com/simp/pupmod-simp-auditd
    augeasproviders_core: https://github.com/simp/augeasproviders_core
    augeasproviders_grub: https://github.com/simp/augeasproviders_grub
    concat: https://github.com/simp/puppetlabs-concat
    augeasproviders_ssh: https://github.com/simp/augeasproviders_ssh
    ssh: https://github.com/simp/pupmod-simp-ssh
    sssd: https://github.com/simp/pupmod-simp-sssd
  symlinks:
    ds389: "#{source_dir}"
